#!/usr/bin/env bash

##################### Variables ############################
DRIVE="/dev/DRIVEID"
export country="United Kingdom"
export EFI_SIZE="500MB"
export user="aidan"
export"password"

############################################################

#part1
printf '\033c'

loadkeys uk

################# Partition Drive #############################
sgdisk --zap-all $DRIVE

sgdisk --clear
sgdisk --new=1:0:+500M --typecode=1:ef00 --change-name=1:EFI $DRIVE 
sgdisk --new=2:0:+8G --typecode=2:8200 --change-name=2:cryptswap $DRIVE
sgdisk --new=3:0:0 --typecode=3:8300 --change-name=3:cryptsystem $DRIVE

sgdisk -p $DRIVE
sgdisk -v $DRIVE

###############################################################
# Create a section that maps the labels to uuid's
#################### Format and Encrypt #######################
#Format EFI using FAT32 FS
mkfs.fat -F32 -n EFI /dev/disk/by-partlabel/EFI

#Encrypt System Partition
cryptsetup luksFormat --align-payload=8192 -s 256 -c aes-xts-plain64 /dev/disk/by-partlabel/cryptsystem

# Open the luks container so that I can setup the btrfs volumes
cryptsetup open /dev/disk/by-partlabel/cryptsystem system

# Bring up encrypted swap. No hibernate enabled yet
cryptsetup open --type plain --key-file /dev/urandom /dev/disk/by-partlabel/cryptswap swap
mkswap -L swap /dev/mapper/swap
swapon -L swap
###############################################################

######### Create and mount BTRFS subvolumes
mkfs.btrfs --label system /dev/mapper/system

o=defaults,x-mount.mkdir
#o_btrfs=$o,compress=lzo,ssd,noatime
o_btrfs=$o,compress=zstd,noatime,commit=120,space_cache=v2

mount -t btrfs LABEL=system /mnt

btrfs subvolume create /mnt/@root
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@var
btrfs subvolume create /mnt/@opt
btrfs subvolume create /mnt/@snapshots

umount -R /mnt
# Have an aption to put the opt or any other subvolme on hdd if you want to save space on ssd

mount -t btrfs -o subvol=@root,$o_btrfs LABEL=system /mnt
mount -t btrfs -o subvol=@home,$o_btrfs LABEL=system /mnt/home
mount -t btrfs -o subvol=@var,$o_btrfs LABEL=system /mnt/var
mount -t btrfs -o subvol=@opt,$o_btrfs LABEL=system /mnt/opt
mount -t btrfs -o subvol=@snapshots,$o_btrfs LABEL=system /mnt/.snapshots

mkdir /mnt/boot
mount LABEL=EFI /mnt/boot

###################################################################

grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf

sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf

#add color to pacman commands 
sed -i "/Color/"'s/^#//' /etc/pacman.conf

#Add multilib repo
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

# Use all cores for compilation.
sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf

# Update Mirrors
pacman -Syy reflector --needed --noconfirm
reflector --verbose --country "$country" --age 12 --latest 10 --sort rate --protocol https --save /etc/pacman.d/mirrorlist
pacman -Syy --noconfirm

pacstrap /mnt base base-devel linux linux-lts linux-firmware btrfs-progs

genfstab -L -p /mnt >> /mnt/etc/fstab


echo -e "cryptswap\t/dev/disk/by-partlabel/cryptswap\t/dev/urandom\tswap,offset=2048,cipher=aes-xts-plain64,size=256" >> /etc/crypttab


sed '1,/^#part2$/d' `basename $0` > /mnt/arch_install2.sh
chmod +x /mnt/arch_install2.sh
arch-chroot /mnt ./arch_install2.sh
exit 

#part2
printf '\033c'

pacman -S --noconfirm intel-ucode

# Install video drivers if intel graphics is used
pacman -S --noconfirm xf86-video-intel --noconfirm

#rm /bin/sh
#ln -s dash /bin/sh
##################################################################

export timezone="Europe/London"
ln -sf /usr/share/zoneinfo/${timezone} /etc/localtime
timedatectl set-ntp 1
hwclock --systohc

###################### locales ######################
# 24 hour format
echo 'LC_TIME=en_GB.UTF-8' >> /etc/locale.conf
echo 'KEYMAP=uk' >> /etc/vconsole.conf
sed -i "/en_GB.UTF-8 UTF-8/s/^#//" /etc/locale.gen
locale-gen


# timedatectl list-timezones
#timedatectl set-timezone America/Los_Angeles
#hostnamectl set-hostname $hostname
####################################################

############ Hostname & /etc/hosts #################
# Hostname
export hostname='laptop'
echo "$hostname" > /etc/hostname

#Set up host file
echo -e "\n127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t${hostname}.localdomain\t$hostname" > /etc/hosts
#####################################################

sed -i '/^HOOKS=/c\HOOKS=(base systemd autodetect sd-vconsole keyboard keymap modconf block sd-encrypt btrfs filesystems resume fsck)' /etc/mkinitcpio.conf
mkinitcpio -p linux
mkinitcpio -p linux-lts

pacman -S --needed grub
grub-install --root-directory=/mnt $DRIVE
grub-mkconfig -o /mnt/boot/grub/grub.cfg

grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf

sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf

#add color to pacman commands 
sed -i "/Color/"'s/^#//' /etc/pacman.conf

#Add multilib repo
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

# Use all cores for compilation.
sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf


useradd -m -G power,audio,wheel,storage $user -s /usr/bin/zsh
echo "${user}:${password}" | chpasswd

# Let users in wheel group run sudo commands without password for automated paru install
sed -i '/^# %wheel ALL=(ALL) NOPASSWD: ALL/s/^# //' /etc/sudoers

git clone https://aur.archlinux.org/paru.git 
cd paru
su -c "makepkg -si" -s /bin/sh $user
cd /root/Nescafe-ArchInstall
rm -r paru

sed -i "s/^#BottomUp$/BottomUp/" /etc/paru.conf


# Most important command! Get rid of the beep!
rmmod pcspkr
echo "blacklist pcspkr" >/etc/modprobe.d/nobeep.conf


# Reconfigure sudo, so that a password is need to elevate privileges.
sed -i '/^# %wheel ALL=(ALL) ALL/s/# //' /etc/sudoers # Uncomment line with sed
sed -i '/^%wheel ALL=(ALL) NOPASSWD: ALL/s/^/# /' /etc/sudoers # Comment line with sed


#systemctl enable NetworkManager.service 
#systemctl enable sshd
